/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.LoginController;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Mauricio Herrera
 */
public class ModuloRoot extends javax.swing.JFrame {

    /**
     * Creates new form Modulo1
     */
    int x,

    /**
     * Creates new form Modulo1
     */
    y;
    boolean maximize = false;
    String VistaActual = "";
    
    public LoginController login;
    
    public ModuloRoot() {
        initComponents();
        this.getContentPane().setBackground(new Color(34, 41, 50));
        setIconImage(new ImageIcon(getClass().getResource("/icons/Link_35px.png")).getImage());
        setTitle("Quiicks V 1.0 - RC 2017-09-17");
        id_userlog.setVisible(false);
//        idpersonaOld.setVisible(false);
//        idUsuarioOld.setVisible(false);
//        idRolxuserOld.setVisible(false);
//        idEmpresaOld.setVisible(false);
//        idSedeOld.setVisible(false);
//        usuarioOld.setVisible(false);
//        idRolOld.setVisible(false);
//        idMusculoUpdate.setVisible(false);
//        idEjercicioUpdate.setVisible(false);
//        lblPayIdUser.setVisible(false);
//        lblIdPagoAction.setVisible(false);
        // setSize(1024, 720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupTblUsers = new javax.swing.JPopupMenu();
        mnuAsocFinger = new javax.swing.JMenuItem();
        mnuUpdate = new javax.swing.JMenuItem();
        mnuDelete = new javax.swing.JMenuItem();
        mnuGenerarPago = new javax.swing.JMenuItem();
        mnuHistoryPays = new javax.swing.JMenuItem();
        mnuAddRutina = new javax.swing.JMenuItem();
        mnuMedidasUser = new javax.swing.JMenuItem();
        popupTblMusculos = new javax.swing.JPopupMenu();
        mnuUpdateMusculo = new javax.swing.JMenuItem();
        mnuDeleteMusculo = new javax.swing.JMenuItem();
        popupEjercicios = new javax.swing.JPopupMenu();
        mnuUpdateEjercicio = new javax.swing.JMenuItem();
        mnuDeleteEjercicio = new javax.swing.JMenuItem();
        popupPagosService = new javax.swing.JPopupMenu();
        mnuBusqueda = new javax.swing.JMenuItem();
        poopupHistoryPays = new javax.swing.JPopupMenu();
        mnuEditFechasPagos = new javax.swing.JMenuItem();
        mnuDeletePagos = new javax.swing.JMenuItem();
        popupTbEmpresas = new javax.swing.JPopupMenu();
        mnuNewSede = new javax.swing.JMenuItem();
        mnuEditEmpresa = new javax.swing.JMenuItem();
        mnuDeleteEmpresa = new javax.swing.JMenuItem();
        popupTblRoles = new javax.swing.JPopupMenu();
        mnuEditRol = new javax.swing.JMenuItem();
        mnuDeleteRol = new javax.swing.JMenuItem();
        mnuPerfilxRol = new javax.swing.JMenuItem();
        popupTblPerfil = new javax.swing.JPopupMenu();
        mnuEditPerfil = new javax.swing.JMenuItem();
        mnuDeletePerfil = new javax.swing.JMenuItem();
        PnMenuPrincipal = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        onOff = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        UserLogPicture = new com.bolivia.label.CLabel();
        nomUserLog = new javax.swing.JLabel();
        nomRolUserlog = new javax.swing.JLabel();
        btnListUsers = new javax.swing.JButton();
        btnAsistencias = new javax.swing.JButton();
        btnAsistenciaManual = new javax.swing.JButton();
        id_userlog = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        btnEmpresas = new javax.swing.JButton();
        btnTransaccionCaja = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnTransaccionCaja1 = new javax.swing.JButton();
        btnPerfilxRol = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnEmpresas = new javax.swing.JPanel();
        pnHeaderEmpresas = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        txtDirEmpresa = new javax.swing.JTextField();
        txtNomEmpresa = new javax.swing.JTextField();
        txtDocNit = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        txtTelEmpresa = new javax.swing.JTextField();
        btnAdjuntarfoto = new javax.swing.JButton();
        jLabel87 = new javax.swing.JLabel();
        btnGuardarEmpresa = new javax.swing.JButton();
        btnCancelarEmpresa = new javax.swing.JButton();
        jPanel54 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtFindUser = new javax.swing.JTextField();
        btnFindUser = new javax.swing.JButton();
        lblLogoEmpresa = new com.bolivia.label.CLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpresas = new javax.swing.JTable();
        pnRoles = new javax.swing.JPanel();
        pnHeaderRoles = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        txtDescRol = new javax.swing.JTextField();
        btnGuardarRol = new javax.swing.JButton();
        btnCancelarRol = new javax.swing.JButton();
        cboEstadoRol = new javax.swing.JComboBox<>();
        jPanel57 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtFindUser1 = new javax.swing.JTextField();
        btnFindUser1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRoles = new javax.swing.JTable();
        pnPerfil = new javax.swing.JPanel();
        pnHeaderRoles1 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        txtDescPerfil = new javax.swing.JTextField();
        btnGuardaPerfil = new javax.swing.JButton();
        btnCancelarPerfil = new javax.swing.JButton();
        cboEstadoPerfil = new javax.swing.JComboBox<>();
        jPanel60 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtFindUser2 = new javax.swing.JTextField();
        btnFindUser2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPerfiles = new javax.swing.JTable();

        mnuAsocFinger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Finger18px.png"))); // NOI18N
        mnuAsocFinger.setText("Asociar Huellas");
        popupTblUsers.add(mnuAsocFinger);

        mnuUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit18px.png"))); // NOI18N
        mnuUpdate.setText("Editar");
        popupTblUsers.add(mnuUpdate);

        mnuDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Eraser.png"))); // NOI18N
        mnuDelete.setText("Eliminar");
        popupTblUsers.add(mnuDelete);

        mnuGenerarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Pay.png"))); // NOI18N
        mnuGenerarPago.setText("Generar Pago");
        popupTblUsers.add(mnuGenerarPago);

        mnuHistoryPays.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HistoryPays.png"))); // NOI18N
        mnuHistoryPays.setText("Ver Pagos");
        popupTblUsers.add(mnuHistoryPays);

        mnuAddRutina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Rutina.png"))); // NOI18N
        mnuAddRutina.setText("Asignar Rutina");
        mnuAddRutina.setEnabled(false);
        popupTblUsers.add(mnuAddRutina);

        mnuMedidasUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Sewing Tape Measure_18px.png"))); // NOI18N
        mnuMedidasUser.setText("Tomar Medidas");
        mnuMedidasUser.setEnabled(false);
        popupTblUsers.add(mnuMedidasUser);

        mnuUpdateMusculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit18px.png"))); // NOI18N
        mnuUpdateMusculo.setText("Editar");
        popupTblMusculos.add(mnuUpdateMusculo);

        mnuDeleteMusculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Eraser.png"))); // NOI18N
        mnuDeleteMusculo.setText("Eliminar");
        popupTblMusculos.add(mnuDeleteMusculo);

        mnuUpdateEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit18px.png"))); // NOI18N
        mnuUpdateEjercicio.setText("Editar");
        popupEjercicios.add(mnuUpdateEjercicio);

        mnuDeleteEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Eraser.png"))); // NOI18N
        mnuDeleteEjercicio.setText("Eliminar");
        popupEjercicios.add(mnuDeleteEjercicio);

        mnuBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit18px.png"))); // NOI18N
        mnuBusqueda.setText("Buscar");
        popupPagosService.add(mnuBusqueda);

        mnuEditFechasPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit18px.png"))); // NOI18N
        mnuEditFechasPagos.setText("Editar");
        poopupHistoryPays.add(mnuEditFechasPagos);

        mnuDeletePagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Eraser.png"))); // NOI18N
        mnuDeletePagos.setText("Eliminar");
        poopupHistoryPays.add(mnuDeletePagos);

        mnuNewSede.setText("Nueva Sede");
        popupTbEmpresas.add(mnuNewSede);

        mnuEditEmpresa.setText("Editar");
        popupTbEmpresas.add(mnuEditEmpresa);

        mnuDeleteEmpresa.setText("Eliminar");
        popupTbEmpresas.add(mnuDeleteEmpresa);

        mnuEditRol.setText("Editar");
        popupTblRoles.add(mnuEditRol);

        mnuDeleteRol.setText("Eliminar");
        popupTblRoles.add(mnuDeleteRol);

        mnuPerfilxRol.setText("Asignar Perfiles");
        popupTblRoles.add(mnuPerfilxRol);

        mnuEditPerfil.setText("Editar");
        popupTblPerfil.add(mnuEditPerfil);

        mnuDeletePerfil.setText("Eliminar");
        popupTblPerfil.add(mnuDeletePerfil);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(54, 63, 73));
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        setLocationByPlatform(true);

        PnMenuPrincipal.setBackground(new java.awt.Color(34, 41, 50));
        PnMenuPrincipal.setPreferredSize(new java.awt.Dimension(200, 631));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gestión De Usuarios");

        onOff.setBackground(new java.awt.Color(255, 0, 0));
        onOff.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        onOff.setForeground(new java.awt.Color(255, 255, 255));
        onOff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        onOff.setText("OFF");
        onOff.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingresos");

        UserLogPicture.setBackground(new java.awt.Color(255, 255, 255));
        UserLogPicture.setForeground(new java.awt.Color(255, 255, 255));
        UserLogPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/userDefault.png"))); // NOI18N
        UserLogPicture.setText("");

        nomUserLog.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        nomUserLog.setForeground(new java.awt.Color(255, 255, 255));
        nomUserLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomUserLog.setText("Datos Admin");

        nomRolUserlog.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        nomRolUserlog.setForeground(new java.awt.Color(255, 255, 255));
        nomRolUserlog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomRolUserlog.setText("Datos Admin");
        nomRolUserlog.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnListUsers.setBackground(new java.awt.Color(54, 63, 73));
        btnListUsers.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnListUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnListUsers.setText("Lista de Usuarios");
        btnListUsers.setBorder(null);
        btnListUsers.setBorderPainted(false);
        btnListUsers.setContentAreaFilled(false);
        btnListUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListUsers.setFocusPainted(false);
        btnListUsers.setHideActionText(true);
        btnListUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListUsers.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnListUsers.setIconTextGap(1);

        btnAsistencias.setBackground(new java.awt.Color(54, 63, 73));
        btnAsistencias.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAsistencias.setForeground(new java.awt.Color(255, 255, 255));
        btnAsistencias.setText("Verificar Asistencias");
        btnAsistencias.setBorder(null);
        btnAsistencias.setBorderPainted(false);
        btnAsistencias.setContentAreaFilled(false);
        btnAsistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistencias.setFocusPainted(false);
        btnAsistencias.setHideActionText(true);
        btnAsistencias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsistencias.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAsistencias.setIconTextGap(1);

        btnAsistenciaManual.setBackground(new java.awt.Color(54, 63, 73));
        btnAsistenciaManual.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAsistenciaManual.setForeground(new java.awt.Color(255, 255, 255));
        btnAsistenciaManual.setText("Asistencia Manual");
        btnAsistenciaManual.setBorder(null);
        btnAsistenciaManual.setBorderPainted(false);
        btnAsistenciaManual.setContentAreaFilled(false);
        btnAsistenciaManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistenciaManual.setFocusPainted(false);
        btnAsistenciaManual.setHideActionText(true);
        btnAsistenciaManual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsistenciaManual.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAsistenciaManual.setIconTextGap(1);

        id_userlog.setEditable(false);
        id_userlog.setBackground(new java.awt.Color(34, 41, 50));
        id_userlog.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        id_userlog.setForeground(new java.awt.Color(255, 255, 255));
        id_userlog.setBorder(null);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Configuración");

        btnEmpresas.setBackground(new java.awt.Color(54, 63, 73));
        btnEmpresas.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnEmpresas.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpresas.setText("Lista de Empresas");
        btnEmpresas.setBorder(null);
        btnEmpresas.setBorderPainted(false);
        btnEmpresas.setContentAreaFilled(false);
        btnEmpresas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpresas.setFocusPainted(false);
        btnEmpresas.setHideActionText(true);
        btnEmpresas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpresas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEmpresas.setIconTextGap(1);

        btnTransaccionCaja.setBackground(new java.awt.Color(54, 63, 73));
        btnTransaccionCaja.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTransaccionCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaccionCaja.setText("Mi Caja");
        btnTransaccionCaja.setBorder(null);
        btnTransaccionCaja.setBorderPainted(false);
        btnTransaccionCaja.setContentAreaFilled(false);
        btnTransaccionCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaccionCaja.setFocusPainted(false);
        btnTransaccionCaja.setHideActionText(true);
        btnTransaccionCaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaccionCaja.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTransaccionCaja.setIconTextGap(1);
        btnTransaccionCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionCajaActionPerformed(evt);
            }
        });

        btnProveedores.setBackground(new java.awt.Color(54, 63, 73));
        btnProveedores.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores.setText("Lista Proveedores");
        btnProveedores.setBorder(null);
        btnProveedores.setBorderPainted(false);
        btnProveedores.setContentAreaFilled(false);
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.setFocusPainted(false);
        btnProveedores.setHideActionText(true);
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProveedores.setIconTextGap(1);

        btnUsuarios.setBackground(new java.awt.Color(54, 63, 73));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Lista de Musculos");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.setHideActionText(true);
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setIconTextGap(1);

        btnRoles.setBackground(new java.awt.Color(54, 63, 73));
        btnRoles.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnRoles.setForeground(new java.awt.Color(255, 255, 255));
        btnRoles.setText("Lista de Roles");
        btnRoles.setBorder(null);
        btnRoles.setBorderPainted(false);
        btnRoles.setContentAreaFilled(false);
        btnRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRoles.setFocusPainted(false);
        btnRoles.setHideActionText(true);
        btnRoles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRoles.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRoles.setIconTextGap(1);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Modulos");

        btnTransaccionCaja1.setBackground(new java.awt.Color(54, 63, 73));
        btnTransaccionCaja1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTransaccionCaja1.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaccionCaja1.setText("Mi Caja");
        btnTransaccionCaja1.setBorder(null);
        btnTransaccionCaja1.setBorderPainted(false);
        btnTransaccionCaja1.setContentAreaFilled(false);
        btnTransaccionCaja1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaccionCaja1.setFocusPainted(false);
        btnTransaccionCaja1.setHideActionText(true);
        btnTransaccionCaja1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaccionCaja1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTransaccionCaja1.setIconTextGap(1);
        btnTransaccionCaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionCaja1ActionPerformed(evt);
            }
        });

        btnPerfilxRol.setBackground(new java.awt.Color(54, 63, 73));
        btnPerfilxRol.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnPerfilxRol.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfilxRol.setText("Asignar Perfil a Rol");
        btnPerfilxRol.setBorder(null);
        btnPerfilxRol.setBorderPainted(false);
        btnPerfilxRol.setContentAreaFilled(false);
        btnPerfilxRol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfilxRol.setFocusPainted(false);
        btnPerfilxRol.setHideActionText(true);
        btnPerfilxRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfilxRol.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPerfilxRol.setIconTextGap(1);

        btnPerfil.setBackground(new java.awt.Color(54, 63, 73));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Lista Perfiles");
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setFocusPainted(false);
        btnPerfil.setHideActionText(true);
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIconTextGap(1);

        javax.swing.GroupLayout PnMenuPrincipalLayout = new javax.swing.GroupLayout(PnMenuPrincipal);
        PnMenuPrincipal.setLayout(PnMenuPrincipalLayout);
        PnMenuPrincipalLayout.setHorizontalGroup(
            PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnMenuPrincipalLayout.createSequentialGroup()
                        .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomRolUserlog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomUserLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(id_userlog))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnMenuPrincipalLayout.createSequentialGroup()
                                .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAsistenciaManual)
                                            .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                                                .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnListUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAsistencias))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(onOff, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel32)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(UserLogPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEmpresas))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnProveedores))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUsuarios))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRoles))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnTransaccionCaja))))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnTransaccionCaja1))))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPerfilxRol))
                    .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPerfil)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PnMenuPrincipalLayout.setVerticalGroup(
            PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserLogPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomRolUserlog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onOff)
                    .addComponent(btnAsistencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsistenciaManual)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransaccionCaja1)
                .addGap(43, 43, 43)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransaccionCaja)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpresas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerfil)
                .addGap(27, 27, 27)
                .addComponent(btnPerfilxRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(id_userlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PnMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnMenuPrincipalLayout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(556, Short.MAX_VALUE)))
        );

        getContentPane().add(PnMenuPrincipal, java.awt.BorderLayout.LINE_START);

        jLayeredPane1.setBackground(new java.awt.Color(34, 41, 50));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnEmpresas.setBackground(new java.awt.Color(54, 63, 73));
        pnEmpresas.setLayout(new java.awt.BorderLayout());

        pnHeaderEmpresas.setBackground(new java.awt.Color(54, 63, 73));
        pnHeaderEmpresas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion de Empresas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnHeaderEmpresas.setPreferredSize(new java.awt.Dimension(840, 180));
        pnHeaderEmpresas.setLayout(new java.awt.BorderLayout());

        jPanel52.setBackground(new java.awt.Color(54, 63, 73));
        jPanel52.setPreferredSize(new java.awt.Dimension(180, 100));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        pnHeaderEmpresas.add(jPanel52, java.awt.BorderLayout.LINE_START);

        jPanel53.setBackground(new java.awt.Color(54, 63, 73));

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Documento/Nit:");

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Nombre:");

        jLabel84.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Direccion:");

        jLabel85.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Telefono:");

        btnAdjuntarfoto.setBackground(new java.awt.Color(54, 63, 73));
        btnAdjuntarfoto.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAdjuntarfoto.setForeground(new java.awt.Color(255, 255, 255));
        btnAdjuntarfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pic.png"))); // NOI18N
        btnAdjuntarfoto.setText("Seleccione...");
        btnAdjuntarfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAdjuntarfoto.setContentAreaFilled(false);
        btnAdjuntarfoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdjuntarfoto.setFocusPainted(false);
        btnAdjuntarfoto.setHideActionText(true);
        btnAdjuntarfoto.setOpaque(true);
        btnAdjuntarfoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdjuntarfotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdjuntarfotoMouseExited(evt);
            }
        });

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("Logo:");

        btnGuardarEmpresa.setBackground(new java.awt.Color(54, 63, 73));
        btnGuardarEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnGuardarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnGuardarEmpresa.setText("Guardar");
        btnGuardarEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnGuardarEmpresa.setContentAreaFilled(false);
        btnGuardarEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarEmpresa.setFocusPainted(false);
        btnGuardarEmpresa.setHideActionText(true);
        btnGuardarEmpresa.setIconTextGap(1);
        btnGuardarEmpresa.setOpaque(true);
        btnGuardarEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarEmpresaMouseExited(evt);
            }
        });

        btnCancelarEmpresa.setBackground(new java.awt.Color(54, 63, 73));
        btnCancelarEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnCancelarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        btnCancelarEmpresa.setText("Cancelar");
        btnCancelarEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCancelarEmpresa.setContentAreaFilled(false);
        btnCancelarEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarEmpresa.setFocusPainted(false);
        btnCancelarEmpresa.setHideActionText(true);
        btnCancelarEmpresa.setIconTextGap(1);
        btnCancelarEmpresa.setOpaque(true);
        btnCancelarEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarEmpresaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel82)
                    .addComponent(jLabel83)
                    .addComponent(jLabel84)
                    .addComponent(jLabel85)
                    .addComponent(jLabel87))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelEmpresa)
                    .addComponent(txtDirEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(txtNomEmpresa)
                    .addComponent(txtDocNit)
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addComponent(btnAdjuntarfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel82))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel85))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdjuntarfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel87)
                    .addComponent(btnGuardarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnHeaderEmpresas.add(jPanel53, java.awt.BorderLayout.CENTER);

        jPanel54.setBackground(new java.awt.Color(54, 63, 73));
        jPanel54.setPreferredSize(new java.awt.Dimension(180, 100));

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnHeaderEmpresas.add(jPanel54, java.awt.BorderLayout.LINE_END);

        pnEmpresas.add(pnHeaderEmpresas, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 41, 50));
        jLabel13.setText("Documento | Nombre :");

        txtFindUser.setBackground(new java.awt.Color(54, 63, 73));
        txtFindUser.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtFindUser.setForeground(new java.awt.Color(255, 255, 255));
        txtFindUser.setCaretColor(new java.awt.Color(255, 255, 255));

        btnFindUser.setBackground(new java.awt.Color(54, 63, 73));
        btnFindUser.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnFindUser.setForeground(new java.awt.Color(255, 255, 255));
        btnFindUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find.png"))); // NOI18N
        btnFindUser.setText("Buscar");
        btnFindUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnFindUser.setContentAreaFilled(false);
        btnFindUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFindUser.setFocusPainted(false);
        btnFindUser.setHideActionText(true);
        btnFindUser.setIconTextGap(1);
        btnFindUser.setOpaque(true);
        btnFindUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFindUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFindUserMouseExited(evt);
            }
        });

        lblLogoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user40.png"))); // NOI18N
        lblLogoEmpresa.setText("");
        lblLogoEmpresa.setPreferredSize(new java.awt.Dimension(50, 50));

        tblEmpresas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblEmpresas.setForeground(new java.awt.Color(34, 41, 50));
        tblEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpresas.setComponentPopupMenu(popupTbEmpresas);
        tblEmpresas.setGridColor(new java.awt.Color(255, 255, 255));
        tblEmpresas.setSelectionBackground(new java.awt.Color(54, 63, 73));
        tblEmpresas.setShowHorizontalLines(false);
        tblEmpresas.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblEmpresas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFindUser, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindUser, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                        .addComponent(lblLogoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(txtFindUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pnEmpresas.add(jPanel2, java.awt.BorderLayout.EAST);

        pnRoles.setBackground(new java.awt.Color(54, 63, 73));
        pnRoles.setLayout(new java.awt.BorderLayout());

        pnHeaderRoles.setBackground(new java.awt.Color(54, 63, 73));
        pnHeaderRoles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion de Roles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnHeaderRoles.setPreferredSize(new java.awt.Dimension(840, 150));
        pnHeaderRoles.setLayout(new java.awt.BorderLayout());

        jPanel55.setBackground(new java.awt.Color(54, 63, 73));
        jPanel55.setPreferredSize(new java.awt.Dimension(280, 100));

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        pnHeaderRoles.add(jPanel55, java.awt.BorderLayout.LINE_START);

        jPanel56.setBackground(new java.awt.Color(54, 63, 73));

        jLabel86.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Rol:");

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("Estado");

        btnGuardarRol.setBackground(new java.awt.Color(54, 63, 73));
        btnGuardarRol.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnGuardarRol.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnGuardarRol.setText("Guardar");
        btnGuardarRol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnGuardarRol.setContentAreaFilled(false);
        btnGuardarRol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarRol.setFocusPainted(false);
        btnGuardarRol.setHideActionText(true);
        btnGuardarRol.setIconTextGap(1);
        btnGuardarRol.setOpaque(true);
        btnGuardarRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarRolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarRolMouseExited(evt);
            }
        });

        btnCancelarRol.setBackground(new java.awt.Color(54, 63, 73));
        btnCancelarRol.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnCancelarRol.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        btnCancelarRol.setText("Cancelar");
        btnCancelarRol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCancelarRol.setContentAreaFilled(false);
        btnCancelarRol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarRol.setFocusPainted(false);
        btnCancelarRol.setHideActionText(true);
        btnCancelarRol.setIconTextGap(1);
        btnCancelarRol.setOpaque(true);
        btnCancelarRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarRolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarRolMouseExited(evt);
            }
        });

        cboEstadoRol.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cboEstadoRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel86)
                    .addComponent(jLabel88))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel56Layout.createSequentialGroup()
                        .addComponent(btnGuardarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btnCancelarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescRol)
                    .addComponent(cboEstadoRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel86))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(cboEstadoRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarRol)
                    .addComponent(btnCancelarRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pnHeaderRoles.add(jPanel56, java.awt.BorderLayout.CENTER);

        jPanel57.setBackground(new java.awt.Color(54, 63, 73));
        jPanel57.setPreferredSize(new java.awt.Dimension(280, 100));

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnHeaderRoles.add(jPanel57, java.awt.BorderLayout.LINE_END);

        pnRoles.add(pnHeaderRoles, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 41, 50));
        jLabel14.setText("Rol:");

        txtFindUser1.setBackground(new java.awt.Color(54, 63, 73));
        txtFindUser1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtFindUser1.setForeground(new java.awt.Color(255, 255, 255));
        txtFindUser1.setCaretColor(new java.awt.Color(255, 255, 255));

        btnFindUser1.setBackground(new java.awt.Color(54, 63, 73));
        btnFindUser1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnFindUser1.setForeground(new java.awt.Color(255, 255, 255));
        btnFindUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find.png"))); // NOI18N
        btnFindUser1.setText("Buscar");
        btnFindUser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnFindUser1.setContentAreaFilled(false);
        btnFindUser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFindUser1.setFocusPainted(false);
        btnFindUser1.setHideActionText(true);
        btnFindUser1.setIconTextGap(1);
        btnFindUser1.setOpaque(true);
        btnFindUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFindUser1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFindUser1MouseExited(evt);
            }
        });

        tblRoles.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblRoles.setForeground(new java.awt.Color(34, 41, 50));
        tblRoles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblRoles.setComponentPopupMenu(popupTblRoles);
        tblRoles.setGridColor(new java.awt.Color(255, 255, 255));
        tblRoles.setSelectionBackground(new java.awt.Color(54, 63, 73));
        tblRoles.setShowHorizontalLines(false);
        tblRoles.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblRoles);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFindUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFindUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(txtFindUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pnRoles.add(jPanel3, java.awt.BorderLayout.EAST);

        pnPerfil.setBackground(new java.awt.Color(54, 63, 73));
        pnPerfil.setLayout(new java.awt.BorderLayout());

        pnHeaderRoles1.setBackground(new java.awt.Color(54, 63, 73));
        pnHeaderRoles1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion de Perfiles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnHeaderRoles1.setPreferredSize(new java.awt.Dimension(840, 150));
        pnHeaderRoles1.setLayout(new java.awt.BorderLayout());

        jPanel58.setBackground(new java.awt.Color(54, 63, 73));
        jPanel58.setPreferredSize(new java.awt.Dimension(280, 100));

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        pnHeaderRoles1.add(jPanel58, java.awt.BorderLayout.LINE_START);

        jPanel59.setBackground(new java.awt.Color(54, 63, 73));

        jLabel89.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setText("Perfil:");

        jLabel90.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("Estado");

        btnGuardaPerfil.setBackground(new java.awt.Color(54, 63, 73));
        btnGuardaPerfil.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnGuardaPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardaPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnGuardaPerfil.setText("Guardar");
        btnGuardaPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnGuardaPerfil.setContentAreaFilled(false);
        btnGuardaPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardaPerfil.setFocusPainted(false);
        btnGuardaPerfil.setHideActionText(true);
        btnGuardaPerfil.setIconTextGap(1);
        btnGuardaPerfil.setOpaque(true);
        btnGuardaPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardaPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardaPerfilMouseExited(evt);
            }
        });

        btnCancelarPerfil.setBackground(new java.awt.Color(54, 63, 73));
        btnCancelarPerfil.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnCancelarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        btnCancelarPerfil.setText("Cancelar");
        btnCancelarPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCancelarPerfil.setContentAreaFilled(false);
        btnCancelarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarPerfil.setFocusPainted(false);
        btnCancelarPerfil.setHideActionText(true);
        btnCancelarPerfil.setIconTextGap(1);
        btnCancelarPerfil.setOpaque(true);
        btnCancelarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarPerfilMouseExited(evt);
            }
        });

        cboEstadoPerfil.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cboEstadoPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel89)
                    .addComponent(jLabel90))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel59Layout.createSequentialGroup()
                        .addComponent(btnGuardaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescPerfil)
                    .addComponent(cboEstadoPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel89))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90)
                    .addComponent(cboEstadoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardaPerfil)
                    .addComponent(btnCancelarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pnHeaderRoles1.add(jPanel59, java.awt.BorderLayout.CENTER);

        jPanel60.setBackground(new java.awt.Color(54, 63, 73));
        jPanel60.setPreferredSize(new java.awt.Dimension(280, 100));

        javax.swing.GroupLayout jPanel60Layout = new javax.swing.GroupLayout(jPanel60);
        jPanel60.setLayout(jPanel60Layout);
        jPanel60Layout.setHorizontalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel60Layout.setVerticalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnHeaderRoles1.add(jPanel60, java.awt.BorderLayout.LINE_END);

        pnPerfil.add(pnHeaderRoles1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(34, 41, 50));
        jLabel16.setText("Rol:");

        txtFindUser2.setBackground(new java.awt.Color(54, 63, 73));
        txtFindUser2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtFindUser2.setForeground(new java.awt.Color(255, 255, 255));
        txtFindUser2.setCaretColor(new java.awt.Color(255, 255, 255));

        btnFindUser2.setBackground(new java.awt.Color(54, 63, 73));
        btnFindUser2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnFindUser2.setForeground(new java.awt.Color(255, 255, 255));
        btnFindUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find.png"))); // NOI18N
        btnFindUser2.setText("Buscar");
        btnFindUser2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnFindUser2.setContentAreaFilled(false);
        btnFindUser2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFindUser2.setFocusPainted(false);
        btnFindUser2.setHideActionText(true);
        btnFindUser2.setIconTextGap(1);
        btnFindUser2.setOpaque(true);
        btnFindUser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFindUser2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFindUser2MouseExited(evt);
            }
        });

        tblPerfiles.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblPerfiles.setForeground(new java.awt.Color(34, 41, 50));
        tblPerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPerfiles.setComponentPopupMenu(popupTblPerfil);
        tblPerfiles.setGridColor(new java.awt.Color(255, 255, 255));
        tblPerfiles.setSelectionBackground(new java.awt.Color(54, 63, 73));
        tblPerfiles.setShowHorizontalLines(false);
        tblPerfiles.setShowVerticalLines(false);
        jScrollPane3.setViewportView(tblPerfiles);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFindUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFindUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(txtFindUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pnPerfil.add(jPanel4, java.awt.BorderLayout.EAST);

        jLayeredPane1.setLayer(pnEmpresas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pnRoles, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.setLayer(pnPerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnRoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnRoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransaccionCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaccionCajaActionPerformed

    private void btnAdjuntarfotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdjuntarfotoMouseEntered
        btnAdjuntarfoto.setBackground(new Color(124, 124, 124));
    }//GEN-LAST:event_btnAdjuntarfotoMouseEntered

    private void btnAdjuntarfotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdjuntarfotoMouseExited
        btnAdjuntarfoto.setBackground(new Color(54, 63, 73));
    }//GEN-LAST:event_btnAdjuntarfotoMouseExited

    private void btnGuardarEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEmpresaMouseEntered
        btnGuardarEmpresa.setBackground(new Color(124, 124, 124));
    }//GEN-LAST:event_btnGuardarEmpresaMouseEntered

    private void btnGuardarEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEmpresaMouseExited
        btnGuardarEmpresa.setBackground(new Color(54, 63, 73));
    }//GEN-LAST:event_btnGuardarEmpresaMouseExited

    private void btnCancelarEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEmpresaMouseEntered
        btnCancelarEmpresa.setBackground(new Color(124, 124, 124));
    }//GEN-LAST:event_btnCancelarEmpresaMouseEntered

    private void btnCancelarEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEmpresaMouseExited
        btnCancelarEmpresa.setBackground(new Color(54, 63, 73));
    }//GEN-LAST:event_btnCancelarEmpresaMouseExited

    private void btnFindUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindUserMouseEntered
        btnFindUser.setBackground(new Color(124, 124, 124));
    }//GEN-LAST:event_btnFindUserMouseEntered

    private void btnFindUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindUserMouseExited
        btnFindUser.setBackground(new Color(54, 63, 73));
    }//GEN-LAST:event_btnFindUserMouseExited

    private void btnGuardarRolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarRolMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarRolMouseEntered

    private void btnGuardarRolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarRolMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarRolMouseExited

    private void btnCancelarRolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarRolMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarRolMouseEntered

    private void btnCancelarRolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarRolMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarRolMouseExited

    private void btnFindUser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindUser1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindUser1MouseEntered

    private void btnFindUser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindUser1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindUser1MouseExited

    private void btnTransaccionCaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionCaja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaccionCaja1ActionPerformed

    private void btnGuardaPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardaPerfilMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardaPerfilMouseEntered

    private void btnGuardaPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardaPerfilMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardaPerfilMouseExited

    private void btnCancelarPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPerfilMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarPerfilMouseEntered

    private void btnCancelarPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPerfilMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarPerfilMouseExited

    private void btnFindUser2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindUser2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindUser2MouseEntered

    private void btnFindUser2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindUser2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindUser2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloRoot().setVisible(true);
            }
        });
    }
    
    public LoginController getLogin() {
        return login;
    }
    
    public void setLogin(LoginController login) {
        this.login = login;
    }
    
    public String getVistaActual() {
        return VistaActual;
    }
    
    public void setVistaActual(String VistaActual) {
        this.VistaActual = VistaActual;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnMenuPrincipal;
    public com.bolivia.label.CLabel UserLogPicture;
    public javax.swing.JButton btnAdjuntarfoto;
    public javax.swing.JButton btnAsistenciaManual;
    public javax.swing.JButton btnAsistencias;
    public javax.swing.JButton btnCancelarEmpresa;
    public javax.swing.JButton btnCancelarPerfil;
    public javax.swing.JButton btnCancelarRol;
    public javax.swing.JButton btnEmpresas;
    public javax.swing.JButton btnFindUser;
    public javax.swing.JButton btnFindUser1;
    public javax.swing.JButton btnFindUser2;
    public javax.swing.JButton btnGuardaPerfil;
    public javax.swing.JButton btnGuardarEmpresa;
    public javax.swing.JButton btnGuardarRol;
    public javax.swing.JButton btnListUsers;
    public javax.swing.JButton btnPerfil;
    public javax.swing.JButton btnPerfilxRol;
    public javax.swing.JButton btnProveedores;
    public javax.swing.JButton btnRoles;
    public javax.swing.JButton btnTransaccionCaja;
    public javax.swing.JButton btnTransaccionCaja1;
    public javax.swing.JButton btnUsuarios;
    public javax.swing.JComboBox<String> cboEstadoPerfil;
    public javax.swing.JComboBox<String> cboEstadoRol;
    public javax.swing.JTextField id_userlog;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public com.bolivia.label.CLabel lblLogoEmpresa;
    private javax.swing.JMenuItem mnuAddRutina;
    public javax.swing.JMenuItem mnuAsocFinger;
    public javax.swing.JMenuItem mnuBusqueda;
    public javax.swing.JMenuItem mnuDelete;
    public javax.swing.JMenuItem mnuDeleteEjercicio;
    public javax.swing.JMenuItem mnuDeleteEmpresa;
    public javax.swing.JMenuItem mnuDeleteMusculo;
    public javax.swing.JMenuItem mnuDeletePagos;
    public javax.swing.JMenuItem mnuDeletePerfil;
    public javax.swing.JMenuItem mnuDeleteRol;
    public javax.swing.JMenuItem mnuEditEmpresa;
    public javax.swing.JMenuItem mnuEditFechasPagos;
    public javax.swing.JMenuItem mnuEditPerfil;
    public javax.swing.JMenuItem mnuEditRol;
    public javax.swing.JMenuItem mnuGenerarPago;
    public javax.swing.JMenuItem mnuHistoryPays;
    public javax.swing.JMenuItem mnuMedidasUser;
    public javax.swing.JMenuItem mnuNewSede;
    public javax.swing.JMenuItem mnuPerfilxRol;
    public javax.swing.JMenuItem mnuUpdate;
    public javax.swing.JMenuItem mnuUpdateEjercicio;
    public javax.swing.JMenuItem mnuUpdateMusculo;
    public javax.swing.JLabel nomRolUserlog;
    public javax.swing.JLabel nomUserLog;
    public javax.swing.JLabel onOff;
    public javax.swing.JPanel pnEmpresas;
    private javax.swing.JPanel pnHeaderEmpresas;
    private javax.swing.JPanel pnHeaderRoles;
    private javax.swing.JPanel pnHeaderRoles1;
    public javax.swing.JPanel pnPerfil;
    public javax.swing.JPanel pnRoles;
    public javax.swing.JPopupMenu poopupHistoryPays;
    private javax.swing.JPopupMenu popupEjercicios;
    private javax.swing.JPopupMenu popupPagosService;
    public javax.swing.JPopupMenu popupTbEmpresas;
    private javax.swing.JPopupMenu popupTblMusculos;
    private javax.swing.JPopupMenu popupTblPerfil;
    private javax.swing.JPopupMenu popupTblRoles;
    private javax.swing.JPopupMenu popupTblUsers;
    public javax.swing.JTable tblEmpresas;
    public javax.swing.JTable tblPerfiles;
    public javax.swing.JTable tblRoles;
    public javax.swing.JTextField txtDescPerfil;
    public javax.swing.JTextField txtDescRol;
    public javax.swing.JTextField txtDirEmpresa;
    public javax.swing.JTextField txtDocNit;
    public javax.swing.JTextField txtFindUser;
    public javax.swing.JTextField txtFindUser1;
    public javax.swing.JTextField txtFindUser2;
    public javax.swing.JTextField txtNomEmpresa;
    public javax.swing.JTextField txtTelEmpresa;
    // End of variables declaration//GEN-END:variables

}
