/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author clopez
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnEmpresas = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnPerfilxRol = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        btnTransaccionCaja = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnTransaccionCaja1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnAsistenciaManual = new javax.swing.JButton();
        btnAsistencias = new javax.swing.JButton();
        onOff = new javax.swing.JLabel();
        btnListUsers = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEmpresas.setBackground(new java.awt.Color(54, 63, 73));
        btnEmpresas.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnEmpresas.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpresas.setText("Lista de Empresas");
        btnEmpresas.setBorder(null);
        btnEmpresas.setBorderPainted(false);
        btnEmpresas.setContentAreaFilled(false);
        btnEmpresas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpresas.setFocusPainted(false);
        btnEmpresas.setHideActionText(true);
        btnEmpresas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpresas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEmpresas.setIconTextGap(1);

        btnRoles.setBackground(new java.awt.Color(54, 63, 73));
        btnRoles.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnRoles.setForeground(new java.awt.Color(255, 255, 255));
        btnRoles.setText("Lista de Roles");
        btnRoles.setBorder(null);
        btnRoles.setBorderPainted(false);
        btnRoles.setContentAreaFilled(false);
        btnRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRoles.setFocusPainted(false);
        btnRoles.setHideActionText(true);
        btnRoles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRoles.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRoles.setIconTextGap(1);

        btnPerfil.setBackground(new java.awt.Color(54, 63, 73));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Lista Perfiles");
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setFocusPainted(false);
        btnPerfil.setHideActionText(true);
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIconTextGap(1);

        btnPerfilxRol.setBackground(new java.awt.Color(54, 63, 73));
        btnPerfilxRol.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnPerfilxRol.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfilxRol.setText("Asignar Perfil a Rol");
        btnPerfilxRol.setBorder(null);
        btnPerfilxRol.setBorderPainted(false);
        btnPerfilxRol.setContentAreaFilled(false);
        btnPerfilxRol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfilxRol.setFocusPainted(false);
        btnPerfilxRol.setHideActionText(true);
        btnPerfilxRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfilxRol.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPerfilxRol.setIconTextGap(1);

        btnProveedores.setBackground(new java.awt.Color(54, 63, 73));
        btnProveedores.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores.setText("Lista Proveedores");
        btnProveedores.setBorder(null);
        btnProveedores.setBorderPainted(false);
        btnProveedores.setContentAreaFilled(false);
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.setFocusPainted(false);
        btnProveedores.setHideActionText(true);
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProveedores.setIconTextGap(1);

        btnUsuarios.setBackground(new java.awt.Color(54, 63, 73));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Lista de Musculos");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.setHideActionText(true);
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setIconTextGap(1);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Configuración");

        btnTransaccionCaja.setBackground(new java.awt.Color(54, 63, 73));
        btnTransaccionCaja.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTransaccionCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaccionCaja.setText("Mi Caja");
        btnTransaccionCaja.setBorder(null);
        btnTransaccionCaja.setBorderPainted(false);
        btnTransaccionCaja.setContentAreaFilled(false);
        btnTransaccionCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaccionCaja.setFocusPainted(false);
        btnTransaccionCaja.setHideActionText(true);
        btnTransaccionCaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaccionCaja.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTransaccionCaja.setIconTextGap(1);
        btnTransaccionCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionCajaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingresos");

        btnTransaccionCaja1.setBackground(new java.awt.Color(54, 63, 73));
        btnTransaccionCaja1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTransaccionCaja1.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaccionCaja1.setText("Mi Caja");
        btnTransaccionCaja1.setBorder(null);
        btnTransaccionCaja1.setBorderPainted(false);
        btnTransaccionCaja1.setContentAreaFilled(false);
        btnTransaccionCaja1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaccionCaja1.setFocusPainted(false);
        btnTransaccionCaja1.setHideActionText(true);
        btnTransaccionCaja1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaccionCaja1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTransaccionCaja1.setIconTextGap(1);
        btnTransaccionCaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionCaja1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Modulos");

        btnAsistenciaManual.setBackground(new java.awt.Color(54, 63, 73));
        btnAsistenciaManual.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAsistenciaManual.setForeground(new java.awt.Color(255, 255, 255));
        btnAsistenciaManual.setText("Asistencia Manual");
        btnAsistenciaManual.setBorder(null);
        btnAsistenciaManual.setBorderPainted(false);
        btnAsistenciaManual.setContentAreaFilled(false);
        btnAsistenciaManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistenciaManual.setFocusPainted(false);
        btnAsistenciaManual.setHideActionText(true);
        btnAsistenciaManual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsistenciaManual.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAsistenciaManual.setIconTextGap(1);

        btnAsistencias.setBackground(new java.awt.Color(54, 63, 73));
        btnAsistencias.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAsistencias.setForeground(new java.awt.Color(255, 255, 255));
        btnAsistencias.setText("Verificar Asistencias");
        btnAsistencias.setBorder(null);
        btnAsistencias.setBorderPainted(false);
        btnAsistencias.setContentAreaFilled(false);
        btnAsistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistencias.setFocusPainted(false);
        btnAsistencias.setHideActionText(true);
        btnAsistencias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsistencias.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAsistencias.setIconTextGap(1);

        onOff.setBackground(new java.awt.Color(255, 0, 0));
        onOff.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        onOff.setForeground(new java.awt.Color(255, 255, 255));
        onOff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        onOff.setText("OFF");
        onOff.setOpaque(true);

        btnListUsers.setBackground(new java.awt.Color(54, 63, 73));
        btnListUsers.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnListUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnListUsers.setText("Lista de Usuarios");
        btnListUsers.setBorder(null);
        btnListUsers.setBorderPainted(false);
        btnListUsers.setContentAreaFilled(false);
        btnListUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListUsers.setFocusPainted(false);
        btnListUsers.setHideActionText(true);
        btnListUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListUsers.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnListUsers.setIconTextGap(1);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gestión De Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsuarios)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnProveedores)
                        .addComponent(btnRoles)
                        .addComponent(btnPerfilxRol)
                        .addComponent(btnPerfil)
                        .addComponent(btnEmpresas)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnTransaccionCaja)
                                .addComponent(btnTransaccionCaja1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAsistenciaManual)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnListUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnAsistencias))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(onOff, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel32)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel15)))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onOff)
                    .addComponent(btnAsistencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsistenciaManual)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(7, 7, 7)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransaccionCaja1)
                .addGap(43, 43, 43)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransaccionCaja)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpresas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerfil)
                .addGap(27, 27, 27)
                .addComponent(btnPerfilxRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransaccionCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaccionCajaActionPerformed

    private void btnTransaccionCaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionCaja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaccionCaja1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAsistenciaManual;
    public javax.swing.JButton btnAsistencias;
    public javax.swing.JButton btnEmpresas;
    public javax.swing.JButton btnListUsers;
    public javax.swing.JButton btnPerfil;
    public javax.swing.JButton btnPerfilxRol;
    public javax.swing.JButton btnProveedores;
    public javax.swing.JButton btnRoles;
    public javax.swing.JButton btnTransaccionCaja;
    public javax.swing.JButton btnTransaccionCaja1;
    public javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel onOff;
    // End of variables declaration//GEN-END:variables
}
