package Views.Modales;

import Controllers.GetPrincipalController;
import Controllers.PrincipalController;
import Pojos.Unidad;
import Pojos.Usuario;
import Pojos.categoria;
import Pojos.iva;
import Pojos.producto;
import java.sql.SQLException;
import Views.Modulo1;
import Views.Modulo2;
import ds.desktop.notify.DesktopNotify;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class NuevoProducto extends javax.swing.JDialog {

    /**
     * Creates new form CategoriasRegistrar
     */
    Modulo2 M2;
    private PrincipalController prc;
    Border Linea;
    Border Linea2;

    public NuevoProducto(java.awt.Frame parent, boolean modal, PrincipalController p) throws SQLException {
        super(parent, modal);
        initComponents();
        System.out.println("inicio edit");
        this.setLocationRelativeTo(null);
        Linea = BorderFactory.createLineBorder(Color.RED, 2);
        Linea2 = BorderFactory.createLineBorder(Color.GRAY, 1);
        prc = p;
        inicarCarga();

    }

    public void inicarCarga() {
        //codigo.setText("" + controladorProducto.ventaProduct.getSecuencia().NumeradorObjecto("sq_mproducto"));
        codigo.setText("1");

        iva.removeAllItems();
        for (iva listIva : (ArrayList<iva>) prc.getI().List()) {
            iva.addItem(listIva);
        }
        categoria.removeAllItems();
        for (categoria listcate : (ArrayList<categoria>) prc.getC().List()) {
            categoria.addItem(listcate);
        }
        uni.removeAllItems();
        for (Unidad listcate : (ArrayList<Unidad>) prc.getU().List()) {
            uni.addItem(listcate);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        linea1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uni = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        costoF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        iva = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        precioVenta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox();
        BtnNewProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Clientes");
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setMinimumSize(new java.awt.Dimension(540, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(linea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 810, 10));

        jPanel2.setBackground(new java.awt.Color(54, 63, 73));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nuevo Producto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(530, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel2.setText("Categoría");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        uni.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.add(uni, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 230, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel3.setText("Código");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        codigo.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoFocusLost(evt);
            }
        });
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoKeyReleased(evt);
            }
        });
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 380, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFocusLost(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 380, 32));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel7.setText("Costo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        costoF.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        costoF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                costoFFocusLost(evt);
            }
        });
        costoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoFActionPerformed(evt);
            }
        });
        costoF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costoFKeyReleased(evt);
            }
        });
        jPanel1.add(costoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 380, 32));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel8.setText("% IVA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        iva.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.add(iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 380, 32));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel9.setText("Unidad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        cantidad.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadFocusLost(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
        });
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 230, 32));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel10.setText("Precio Venta");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        precioVenta.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        precioVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioVentaFocusLost(evt);
            }
        });
        precioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioVentaKeyReleased(evt);
            }
        });
        jPanel1.add(precioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 230, 32));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel12.setText("Stock");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        stock.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        stock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                stockFocusLost(evt);
            }
        });
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stockKeyReleased(evt);
            }
        });
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 230, 32));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel11.setText("Cantidad");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        categoria.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 380, 32));

        BtnNewProducto.setBackground(new java.awt.Color(54, 63, 73));
        BtnNewProducto.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnNewProducto.setForeground(new java.awt.Color(255, 255, 255));
        BtnNewProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/findWhite.png"))); // NOI18N
        BtnNewProducto.setText("Aceptar");
        BtnNewProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnNewProducto.setContentAreaFilled(false);
        BtnNewProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNewProducto.setFocusPainted(false);
        BtnNewProducto.setHideActionText(true);
        BtnNewProducto.setIconTextGap(3);
        BtnNewProducto.setOpaque(true);
        BtnNewProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnNewProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnNewProductoMouseExited(evt);
            }
        });
        BtnNewProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewProductoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnNewProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoFocusLost

    }//GEN-LAST:event_codigoFocusLost

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed

    }//GEN-LAST:event_codigoActionPerformed

    private void codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyReleased

    }//GEN-LAST:event_codigoKeyReleased

    private void nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusLost
        if (nombre.getText().length() == 0) {
            nombre.setBorder(Linea);
        } else {
            nombre.setBorder(Linea2);
            nombre.setText("" + nombre.getText());
        }
    }//GEN-LAST:event_nombreFocusLost

    private void costoFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costoFFocusLost
        if (isNumero(costoF.getText())) {
            if (costoF.getText().length() == 0 || costoF.getText().equalsIgnoreCase("0")) {
                costoF.setBorder(Linea);
            } else {
                costoF.setBorder(Linea2);
                prc.getC();
                prc.c = (categoria) categoria.getSelectedItem();
                if (prc.c.getGanancia().intValue() > 0) {
                    BigDecimal valorProducto = null;
                    valorProducto = (new BigDecimal(costoF.getText()).add(new BigDecimal(costoF.getText()).multiply(prc.c.getGanancia().divide(new BigDecimal(100)))));
                    this.precioVenta.setText(" " + valorProducto.intValue());
                }
                costoF.setText("" + costoF.getText());
            }
        } else {
            DesktopNotify.showDesktopMessage("Aviso..!", "El campo Costovrecibe solo valores Numericos , Mayores a cero", DesktopNotify.ERROR, 5000L);
        }
    }//GEN-LAST:event_costoFFocusLost

    private void costoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoFActionPerformed

    }//GEN-LAST:event_costoFActionPerformed

    private void costoFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoFKeyReleased

    }//GEN-LAST:event_costoFKeyReleased

    private void cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusLost
        if (isNumero(cantidad.getText())) {
            if (cantidad.getText().length() == 0 || cantidad.getText().equalsIgnoreCase("0")) {
                cantidad.setBorder(Linea);
            } else {
                cantidad.setBorder(Linea2);
                cantidad.setText(" " + cantidad.getText());
            }
        } else {
            DesktopNotify.showDesktopMessage("Aviso..!", "El campo Cantidad recibe solo valores numeros , Mayores a cero", DesktopNotify.ERROR, 5000L);
        }
    }//GEN-LAST:event_cantidadFocusLost

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased

    }//GEN-LAST:event_cantidadKeyReleased

    private void precioVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioVentaFocusLost
        if (isNumero(precioVenta.getText())) {
            if (precioVenta.getText().length() == 0 || precioVenta.getText().equalsIgnoreCase("0")) {
                precioVenta.setBorder(Linea);
            } else {
                precioVenta.setBorder(Linea2);
                precioVenta.setText(" " + precioVenta.getText());
            }
        } else {
            DesktopNotify.showDesktopMessage("Aviso..!", "El campo Precio Venta recibe valores solo numericos , Mayores a cero", DesktopNotify.ERROR, 5000L);
        }
    }//GEN-LAST:event_precioVentaFocusLost

    private void precioVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioVentaKeyReleased

    }//GEN-LAST:event_precioVentaKeyReleased

    private void stockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stockFocusLost
        if (isNumero(stock.getText())) {
            if (stock.getText().length() == 0 || stock.getText().equalsIgnoreCase("0")) {
                stock.setBorder(Linea);
            } else {
                stock.setBorder(Linea2);
                stock.setText(" " + stock.getText());
            }
        } else {
            DesktopNotify.showDesktopMessage("Aviso..!", "El campo Stock recibe solo valores numericos", DesktopNotify.ERROR, 5000L);
        }
    }//GEN-LAST:event_stockFocusLost
    public static boolean isNumero(String Numero) {
        try {
            if (Numero.contains(".")) {
                Double.parseDouble(Numero);
            } else {
                Integer.parseInt(Numero);
            }

            return true;
        } catch (Exception ex) {
            return false;
        }
    }

    public void ValidacionCampos() {
        String mns = "";

    }

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void stockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockKeyReleased

    }//GEN-LAST:event_stockKeyReleased

    private void BtnNewProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNewProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNewProductoMouseEntered

    private void BtnNewProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNewProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNewProductoMouseExited

    private void BtnNewProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewProductoActionPerformed
        producto p = new producto();
        p.setSerieproducto(this.codigo.getText().trim());
        p.setNombreProducto(this.nombre.getText().trim());
        p.setCosto(new BigDecimal(this.costoF.getText().trim()));
        p.setCantidad(Integer.parseInt(this.cantidad.getText().trim()));
        p.setPrecio_venta(new BigDecimal(this.precioVenta.getText().trim()));
        p.setStock(new BigDecimal(this.stock.getText().trim()));
        p.setCategoria((categoria) categoria.getSelectedItem());
        p.setIvaP((iva) iva.getSelectedItem());
        p.setUnidad((Unidad) uni.getSelectedItem());

        prc.getPr().getListProductos().add(p);
        this.dispose();
    }//GEN-LAST:event_BtnNewProductoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CategoriasRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CategoriasRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CategoriasRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CategoriasRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CategoriasRegistrar dialog = new CategoriasRegistrar(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnNewProducto;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox categoria;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField costoF;
    private javax.swing.JComboBox iva;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator linea1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precioVenta;
    private javax.swing.JTextField stock;
    private javax.swing.JComboBox uni;
    // End of variables declaration//GEN-END:variables
}
